cobalt/debug: make build-time dependency on DEBUG_LOCKING obvious
Testing XENO_DEBUG(LOCKING) in #if conditionals may confuse the
build-time dependency engine. Prior to this fix, turning on the
locking debug option without removing cobalt/debug.o may cause
undefined references at next build, such as:

kernel/built-in.o: In function `xnlock_dbg_release':
:(.text+0x111ed8): undefined reference to `xnlock_stats'
kernel/built-in.o: In function `lock_vfile_show':
:(.text+0x1186e8): undefined reference to `xnlock_stats'
kernel/built-in.o: In function `lock_vfile_store':
:(.text+0x118864): undefined reference to `xnlock_stats'