lib/boilerplate: Fix build for mercury
"commit 9da7bde" introduces rt_print_flush_buffers in ancillaries

Fixes the following error "--with-core=mercury" :

   >> ancillaries.c: In function ‘___panic’:
   >> ancillaries.c:129:2: error: implicit declaration of function ‘rt_print_flush_buffers’
   >>   rt_print_flush_buffers();
   >>   ^

Signed-off-by: Ivid Suvarna <ivid.suvarna@gmail.com>