boilerplate: solve compiler warning when libgen.h is included
In boilerplate function 'get_program_name', basename is used.

When libgen.h is included in your program, the basename gets the POSIX
version (no const char*, see 'man basename'): char *basename(char
*path);

This results in the following compiler warning:
boilerplate/setup.h: In function 'const char* get_program_name()':
boilerplate/setup.h:107: error: invalid conversion from 'const char*' to 'char*'
boilerplate/setup.h:107: error:   initializing argument 1 of 'char* __xpg_basename(char*)'

Test application:

int main(int argc, char * const argv[])
{
  return 0;
}

When the libgen.h is not included, the warning is not seen.

This patch solve the above issue by moving the implementation to setup.c
instead of using an inline function.